/*FETCH ALL THE DETAILS OF PUBLIC HOSITAL WITH TOTAL BEDS AVALIABLE*/

SELECT 
    state_id,
    states_in_india,
    pub_hos,
    Pub_Hos_Gen_Beds,
    Pub_Hos_ICU_Beds,
    (pub_hos_gen_beds + pub_hos_icu_beds) AS tot_beds
FROM
    hos_det;



/*FETCH ALL THE DETAILS OF HOSPITAL AND RANK THE TOP STATE WHICH HAS MORE BEDS
 WITH POPULATION DATA AND CREATE TABLE IN THE NAME OF RANK_OF_TOTAL_BEDS*/

﻿﻿CREATE TABLE RANK_OF_TOTAL_BEDS
 SELECT H.STATE_ID,H.STATES_IN_INDIA,C. Population_Data, H.PUB_HOS, H.PRI_HOS, H.TOT_HOS, 
 (H.PUB_HOS_GEN_BEDS + H.PUB_HOS_ICU_BEDS) AS TOT_BEDS_IN_PUB_HOS,
(H.PRI_HOS_GEN_BEDS + H. PRIVATE_HOSPITAL_ICU_BEDS) AS TOT_BEDS_IN_PRI_HOS,
(H.PUB_HOS_GEN_BEDS + H.PUB_HOS_ICU_BEDS + H.PRI_HOS_GEN_BEDS + H.PRIVATE_HOSPITAL_ICU_BEDS) AS TOT_BEDS,
CASE
WHEN
H.PUB_HOS_GEN_BEDS + H.PUB_HOS_ICU_BEDS + H.PRI_HOS_GEN_BEDS + H.PRIVATE_HOSPITAL_ICU_BEDS >= 300000 AND
 H.PUB_HOS_GEN_BEDS + H.PUB_HOS_ICU_BEDS + H.PRI_HOS_GEN_BEDS + H.PRIVATE_HOSPITAL_ICU_BEDS <= 500000

THEN 'HIGHER LEVEL BEDS'

WHEN 
H.PUB_HOS_GEN_BEDS + H.PUB_HOS_ICU_BEDS + H.PRI_HOS_GEN_BEDS + H. PRIVATE_HOSPITAL_ICU_BEDS >= 100000 
AND H.PUB_HOS_GEN_BEDS + H.PUB_HOS_ICU_BEDS + H.PRI_HOS_GEN_BEDS + H.PRIVATE_HOSPITAL_ICU_BEDS <= 290000

THEN 'MEDIUM LEVEL BEDS'

WHEN
H.PUB_HOS_GEN_BEDS + H.PUB_HOS_ICU_BEDS + H. PRI_HOS_GEN_BEDS + H.PRIVATE_HOSPITAL_ICU_BEDS >= 50000
AND H.PUB_HOS_GEN_BEDS + H.PUB_HOS_ICU_BEDS + H.PRI_HOS_GEN_BEDS + H.PRIVATE HOSPITAL_ICU_BEDS <= 99000 
THEN 'NORMAL LEVEL BEDS' 
ELSE 'POOR LEVEL BEDS'
END AS RANK_OF_TOT_BEDS FROM HOS DET H INNER JOIN covid_case C ON
 H.STATE_ID =C.STATE_ID 
 ORDER BY RANK_OF_TOT_BEDS;
 
 /*FETCH TOP 5 STATES WHICH HASE LOW NUMBER OF DECEASED_PERFORMANCE*/

SELECT 
    *
FROM
    covid_case
ORDER BY Deceased_Peformance
LIMIT 5



/*FETCH THE HOSPITAL BEDS DETAILS AND CONFIRMED PERFORMANCE OF EACH STATE AND
 RANK THE STATE WHICH HAS HIGHEST CONFORMED COVID CASES AND   
 CREATE TABLE IN THE NAME OF CONFORMED_PERFORMANCE_BY_EACH_STATE*/

CREATE TABLE CONFORMED_PERFORMANCE_BY_EACH_STATE SELECT R.STATE_ID,C.STATES_IN_INDIA, C.POPULATION_DATA, R. TOT_HOS, R. TOT_BEDS,
C.CONFIRMED_PERFORMANCE,
CASE
WHEN
THEN
WHEN
C.CONFIRMED_PERFORMANCE >= 100000
AND C.CONFIRMED_PERFORMANCE <= 250000
'HIGH AFFECTED'
C.CONFIRMED_PERFORMANCE >= 50000
AND C.CONFIRMED_PERFORMANCE <= 99000
THEN
WHEN
THEN
'MEDIUM AFFECTED'
C.CONFIRMED_PERFORMANCE >= 10000
AND C.CONFIRMED_PERFORMANCE <= 49000
'NORMAL AFFECTED'
ELSE 'LESS AFFECTED'
END AS CONFORMED CASES FROM
RANK_OF_TOTAL_BEDS R INNER JOIN COVID_CASE C ON R.STATE_ID
=
C.STATE_ID ORDER BY CONFORMED_CASES;



/*FETCH THE HOSPITAL DETAILS AND  RECOVERED PATIENTS AND RANK THE STATE WISE HGHER NUMBER
 OF RECOVERY PAITENTS*/
﻿
SELECT H.STATE_ID,H.STATES_IN_INDIA,C.POPULATION_DATA,H.TOT_HOS,C.CONFIRMED_PERFORMANCE, C. RECOVERED_PERFORMANCE, 
CASE
WHEN
c.recovered_performance >= 90000
AND c.recovered_performance <= 200000
THEN
'best recove'
WHEN
c.recovered_performance >= 40000
AND c.recovered_performance <= 89000
THEN
'good recover'
WHEN
c.recovered_performance >= 10000
AND c.recovered_performance <= 49000

THEN
'avg recover'

ELSE 'poor recover'
END AS RANK_BASED_ON_RECOVER
from HOS_DET H INNER JOIN COVID_CASE C ON H.STATE_ID = C.STATE_ID ORDER BY 
RANK_BASED_ON_RECOVER;

/*FETCH ALL THE DETAILS OF HOSPITAL AND COVID PERFORMANCE*/

﻿SELECT
h.*,
C.Confirmed_Performance,
C. Deceased_Peformance,
C. Population_Data,
C.Rank_based_on_Population
from
hos_det h
INNER JOIN
covid_case C ON h.state_id
=
c.State_ID;
